name: Run Ansible playbook
on: [push]

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Ansible playbook
      uses: ansible/ansible-playbook-action@v2
      with:
        playbook: playbook.yml
        inventory: hosts.ini
        extra-vars: |
          var1=value1
          var2=value2

